Remove BB=/bin/busybox and $BB <cmd> in favor of PREFER_APPLETS conf

diff --git a/usr/share/bbinit/init b/usr/share/bbinit/init
--- a/usr/share/bbinit/init
+++ b/usr/share/bbinit/init
@@ -13,20 +13,20 @@ mdev_log=""
 
 FAIL () {
   printf '\n %s \n\n Entering rescue shell. \n' "$1"
-  $BB sh -l
+  sh -l
 }
 
 INFO () { [ $loglevel -gt 1 ] && echo $@ || : ; }
 
-do_mount () { INFO "Mounting $1 on $2"; $BB mount -t $1 $1 $2; }
+do_mount () { INFO "Mounting $1 on $2"; mount -t $1 $1 $2; }
 
 greeting="Preparing initramfs and mounting /proc"
 printf "$greeting"
-$BB mkdir -p /sbin /usr/bin /usr/sbin /proc /sys /dev
-$BB --install -s
+mkdir -p /sbin /usr/bin /usr/sbin /proc /sys /dev
+/bin/busybox --install -s
 mount -t proc proc /proc
 
-for ARG in $($BB cat /proc/cmdline); do
+for ARG in $(cat /proc/cmdline); do
   case "$ARG" in
     *.*=*) ;;
     *=*) eval $ARG ;;
@@ -39,28 +39,28 @@ done
 printf "%d" $loglevel &> /dev/null || loglevel=2
 [ $loglevel -gt 8 ] && loglevel=8
 [ $loglevel -lt 1 ] && loglevel=1
-$BB dmesg -n $loglevel
+dmesg -n $loglevel
 
 [ "x$modprobe_delay" != 'x' ] && \
- $BB sleep "$modprobe_delay" &> /dev/null || \
+ sleep "$modprobe_delay" &> /dev/null || \
   unset modprobe_delay
 
 [ $loglevel -eq 1 ] && printf "\r ${greeting//?/ } \r" || echo
 
 do_mount sysfs /sys
 do_mount devtmpfs /dev
-[ -c /dev/null ] || $BB mknod -m 666 /dev/null c 1 3
+[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3
 
-MODULES_DIR="/lib/modules/$($BB uname -r)"
+MODULES_DIR="/lib/modules/$(uname -r)"
 
 if [ -d "$MODULES_DIR" ] ; then
   INFO "Running depmod"
-  $BB depmod
+  depmod
 fi
 
 if type -p mdev &> /dev/null ; then
   INFO 'Initializing mdev'
-  [ "x$mdev_log" != 'x' ] && $BB touch "$mdev_log"
+  [ "x$mdev_log" != 'x' ] && touch "$mdev_log"
   if [ -e /proc/sys/kernel/hotplug ] ; then 
     echo $(type -p mdev) > /proc/sys/kernel/hotplug
   else
@@ -69,13 +69,13 @@ if type -p mdev &> /dev/null ; then
       uevent $(type -p mdev) &
     fi
   fi
-  $BB mdev -s
+  mdev -s
 fi
 
 do_modprobe () {
   local ARG=
   local OPTS=
-  for ARG in $($BB cat /proc/cmdline); do
+  for ARG in $(cat /proc/cmdline); do
     case "$ARG" in
       *.*) [ "${ARG%%.*}" = "$1" ] && OPTS="$OPTS ${ARG#*.}" ;;
     esac
@@ -83,9 +83,9 @@ do_modprobe () {
   OPTS="$1 $OPTS"
   if [ "x$modprobe_delay" != 'x' ] ; then
     echo modprobe $OPTS
-    [ "$modprobe_delay" = '0' ] || $BB sleep $modprobe_delay
+    [ "$modprobe_delay" = '0' ] || sleep $modprobe_delay
   fi
-  $BB modprobe $OPTS
+  modprobe $OPTS
 }
 
 if [ "x$modules" != 'x' ]; then
@@ -94,7 +94,7 @@ if [ "x$modules" != 'x' ]; then
   done
 fi
 
-modalias_count () { $BB find /sys/ -type f -name modalias | $BB wc -l ; }
+modalias_count () { find /sys/ -type f -name modalias | wc -l ; }
 
 if [ -e /etc/autoscan ] ; then
   printf "Scanning for hardware "
@@ -102,17 +102,17 @@ if [ -e /etc/autoscan ] ; then
   while [ $LOOPS -lt 100 ] ; do
     printf '.'
     pre=$(modalias_count)
-    $BB find /sys/ -type f -name modalias -exec $BB cat {} + | $BB sort -u | while read M ; do
+    find /sys/ -type f -name modalias -exec cat {} + | sort -u | while read M ; do
       do_modprobe $M 2> /dev/null
     done
-    $BB sleep 0.1
+    sleep 0.1
     [ "$pre" -eq $(modalias_count) ] && break
     LOOPS=$((LOOPS+1))
   done
   echo
   INFO "Loading filesystem modules"
-  for M in $($BB find "$MODULES_DIR/kernel/fs" -type f -name '*.ko*') ; do
-    for A in $($BB modinfo -F alias $M) ; do
+  for M in $(find "$MODULES_DIR/kernel/fs" -type f -name '*.ko*') ; do
+    for A in $(modinfo -F alias $M) ; do
       do_modprobe "$A" && break
     done
   done
@@ -140,12 +140,12 @@ timeout=$rootdelay
 
 case "$root" in
   *=*)
-    found_root=$($BB findfs $root)
+    found_root=$(findfs $root)
     while [ $timeout -gt 0 ] && [  "x$found_root" = 'x' ]; do
-      $BB mdev -s
+      mdev -s
       printf " Waiting %d seconds to resolve %s    \r" "$timeout" "$root"
       sleep 1
-      found_root=$($BB findfs $root)
+      found_root=$(findfs $root)
       timeout=$((timeout-1))
     done
     if [ "x$found_root" != 'x' ]; then
@@ -159,9 +159,9 @@ case "$root" in
   ;;
   *)
     while [ ! -e "$root" ] && [ $timeout -gt 0 ]; do
-      $BB mdev -s
+      mdev -s
       printf " Waiting %d seconds for %s to appear     \r" "$timeout" "$root"
-      $BB sleep 1
+      sleep 1
       timeout=$((timeout-1))
     done
     if [ -e "$root" ]; then
@@ -173,7 +173,7 @@ case "$root" in
   ;;
 esac
 
-$BB mkdir -p "$NEWROOT"
+mkdir -p "$NEWROOT"
 
 if ! [ -e "$root" ]; then
   echo
@@ -182,28 +182,28 @@ if ! [ -e "$root" ]; then
   FAIL
 fi
 
-$BB mount -o ro "$root" "$NEWROOT" ||  FAIL "Couldn't mount root FS read-only!"
+mount -o ro "$root" "$NEWROOT" ||  FAIL "Couldn't mount root FS read-only!"
 
 [ "x$init" = 'x' ] && init='/sbin/init'
 [ -f "$NEWROOT/$init" ] || FAIL "$root successfully mounted but no $init found!"
 
-P=$($BB pidof uevent 2> /dev/null)
-[ $? -eq 0 ] && INFO "Stopping ramfs uevent daemon" && $BB kill $P
+P=$(pidof uevent 2> /dev/null)
+[ $? -eq 0 ] && INFO "Stopping ramfs uevent daemon" && kill $P
 
 if [ -f "$mdev_log" ] ; then
   printf '==== preparing to switch_root, up %s sec.\n' \
-    "$($BB cut -d ' ' -f 1 /proc/uptime)" >> "$mdev_log"
+    "$(cut -d ' ' -f 1 /proc/uptime)" >> "$mdev_log"
 fi
 
 INFO "Unmounting initramfs system directories"
-$BB umount /sys 
-$BB mount --move /dev "$NEWROOT/dev"
-$BB umount /proc
+umount /sys 
+mount --move /dev "$NEWROOT/dev"
+umount /proc
 
 cmd=switch_root
 INFO "Executing $cmd and spawning init"
-exec $BB $cmd "$NEWROOT" "$init" $INIT_ARGS
+exec $cmd "$NEWROOT" "$init" $INIT_ARGS
 
-$BB mount -t proc proc /proc
+mount -t proc proc /proc
 FAIL "Couldn't perform $cmd"
 
diff --git a/usr/share/bbinit/utils/pxesrv b/usr/share/bbinit/utils/pxesrv
--- a/usr/share/bbinit/utils/pxesrv
+++ b/usr/share/bbinit/utils/pxesrv
@@ -6,16 +6,15 @@
 set -e
 
 WKDIR=
-BB='/bin/busybox'
 
 trap '
 if [ -d "$WKDIR" ]; then
  for P in udhcpd httpd ftpd; do
   if [ -f $WKDIR/$P.pid ]; then
-   $BB kill $($BB cat $WKDIR/$P.pid) || :
+   kill $(cat $WKDIR/$P.pid) || :
   fi
  done
- $BB rm -r $WKDIR
+ rm -r $WKDIR
 fi
 ' INT EXIT
 
@@ -98,29 +97,29 @@ if [ -n "$BOOT_IMG" ] ; then
   [ -z "$KERNEL" ] || die "Cannot use -b and -k together"
   [ -z "$INITRD" ] || die "Cannot use -b and -f together"
   exist_or_die "$BOOT_IMG"
-  BOOT_IMG=$($BB readlink -f $BOOT_IMG)
+  BOOT_IMG=$(readlink -f $BOOT_IMG)
   isreg_or_die "$BOOT_IMG"
 else
   [ -n "$KERNEL" ] || die 'You must specify a disk image or kernel file to boot'
   exist_or_die "$KERNEL"
-  KERNEL=$($BB readlink -f $KERNEL)
+  KERNEL=$(readlink -f $KERNEL)
   isreg_or_die "$KERNEL"
   if [ -n "$INITRD" ] ; then
     exist_or_die "$INITRD"
-    INITRD=$($BB readlink -f $INITRD)
+    INITRD=$(readlink -f $INITRD)
     isreg_or_die $INITRD
   fi
 fi
 
 
 if [ -n "$SYSLINUX_DIR" ]; then
-  SYSLINUX_DIR=$($BB readlink -f "$SYSLINUX_DIR")
+  SYSLINUX_DIR=$(readlink -f "$SYSLINUX_DIR")
 else
   for D1 in '/' '/usr/' '/usr/local/'; do
     for D2 in '/lib/' '/share/'; do
       for D3 in '/' '/bios/'; do
         if [ -f "$D1/$D2/syslinux/$D3/pxelinux.0" ]; then
-          SYSLINUX_DIR=$($BB readlink -f "$D1/$D2/syslinux/$D3/")
+          SYSLINUX_DIR=$(readlink -f "$D1/$D2/syslinux/$D3/")
           break
         fi
       done
@@ -147,14 +146,14 @@ if [ -z "$NET_DEV" ] && [ -z "$LOCAL_IP" ]; then
 fi
 
 if [ -n "$NET_DEV" ]; then
-  $BB ifconfig "$NET_DEV" > /dev/null || die "Invalid network interface: $NET_DEV"
+  ifconfig "$NET_DEV" > /dev/null || die "Invalid network interface: $NET_DEV"
   if [ -z "$LOCAL_IP" ]; then
-    LOCAL_IP=$($BB ifconfig "$NET_DEV" | $BB awk '/^ *inet addr:/ {sub(/:/," "); print $3}')
+    LOCAL_IP=$(ifconfig "$NET_DEV" | awk '/^ *inet addr:/ {sub(/:/," "); print $3}')
   fi
 else
   if [ -n "$LOCAL_IP" ]; then
-    for IF in $($BB ifconfig | $BB awk '/^[^ \t]/ {print $1}'); do
-      if $BB ifconfig $IF | $BB grep -q "^ *inet addr:${LOCAL_IP//./\\.} "; then
+    for IF in $(ifconfig | awk '/^[^ \t]/ {print $1}'); do
+      if ifconfig $IF | grep -q "^ *inet addr:${LOCAL_IP//./\\.} "; then
         NET_DEV=$IF
         break
       fi
@@ -168,7 +167,7 @@ fi
 
 
 [ -n "$TEMP" ] || TEMP='/tmp'
-WKDIR=$($BB mktemp -d "$TEMP/pxe-XXXXXX")
+WKDIR=$(mktemp -d "$TEMP/pxe-XXXXXX")
 
 cd "$WKDIR"
 
@@ -176,7 +175,7 @@ cd "$WKDIR"
 
 PXECFG='pxelinux.cfg/default'
 
-hexopt () { printf "%s" "$@" | $BB hexdump -ve '/1 "%x"' ; }
+hexopt () { printf "%s" "$@" | hexdump -ve '/1 "%x"' ; }
 
 if [ "$STR_NULL" = 'yes' ] ; then
   BOOTFILEOPT="option 0x43 $(hexopt $BOOTFILE)00"
@@ -186,7 +185,7 @@ else
   CFGFILEOPT="option pxeconffile $PXECFG"
 fi
 
-$BB cat << EOF > "$WKDIR/udhcpd.conf"
+cat << EOF > "$WKDIR/udhcpd.conf"
 start $REMOTE_IP
 end $REMOTE_IP
 sname $LOCAL_IP
@@ -207,8 +206,8 @@ for SRC in \
   "$SYSLINUX_DIR/memdisk"
 do
   [ "x$SRC" = 'x' ] && continue
-  DST=$WKDIR/$($BB basename "$SRC")
-  [ -e "$DST" ] || $BB cp -ai "$SRC" "$DST"
+  DST=$WKDIR/$(basename "$SRC")
+  [ -e "$DST" ] || cp -ai "$SRC" "$DST"
 done
 
 cp -a "$SYSLINUX_DIR/." "$WKDIR/."
@@ -230,7 +229,7 @@ for A in $APPEND; do
   esac
 done
 if [ -z "$IMG_TYPE" ] ; then
-  for A in $($BB blkid "$BOOT_IMG") ; do
+  for A in $(blkid "$BOOT_IMG") ; do
     case "$A" in
       TYPE=*iso*)
         IMG_TYPE=iso
@@ -248,32 +247,32 @@ cat <<  EOF > "$WKDIR/$PXECFG"
 default pxe
 label pxe
   kernel  ${HOST_PATH}memdisk
-  append $APPEND initrd=${HOST_PATH}$($BB basename $BOOT_IMG)
+  append $APPEND initrd=${HOST_PATH}$(basename $BOOT_IMG)
 EOF
 else
 cat <<  EOF > "$WKDIR/$PXECFG"
 default pxe
 label pxe
-  linux ${HOST_PATH}$($BB basename $KERNEL)
+  linux ${HOST_PATH}$(basename $KERNEL)
 EOF
 if [ -n "$INITRD" ]; then
-  APPEND="initrd=${HOST_PATH}$($BB basename $INITRD) $APPEND"
+  APPEND="initrd=${HOST_PATH}$(basename $INITRD) $APPEND"
 fi
 echo append $APPEND >> "$WKDIR/$PXECFG"
 fi
 
-$BB udhcpd -I "$LOCAL_IP" "$WKDIR/udhcpd.conf"
+udhcpd -I "$LOCAL_IP" "$WKDIR/udhcpd.conf"
 
 case "$PROTO" in
 http)
-  $BB httpd -f -p "$LOCAL_IP:80" -h "$WKDIR" &
+  httpd -f -p "$LOCAL_IP:80" -h "$WKDIR" &
   echo $! > "$WKDIR/httpd.pid"
 ;;
 ftp)
-  $BB tcpsvd -vE "$LOCAL_IP" 21 $BB ftpd -vv "$WKDIR" &
+  tcpsvd -vE "$LOCAL_IP" 21 ftpd -vv "$WKDIR" &
   echo $! > "$WKDIR/ftpd.pid"
 ;;
 esac
 
-$BB udpsvd -E "$LOCAL_IP" 69 $BB tftpd -r "$WKDIR"
+udpsvd -E "$LOCAL_IP" 69 tftpd -r "$WKDIR"
 
