Test for odd case where busybox is not a regular file

diff --git a/usr/share/bbinit/utils/bbck b/usr/share/bbinit/utils/bbck
--- a/usr/share/bbinit/utils/bbck
+++ b/usr/share/bbinit/utils/bbck
@@ -48,7 +48,8 @@ case "$TestBB" in
   ;;
 esac
 
-[ -f "$TestBB" ] || die "Cannot find $TestBB"
+[ -e "$TestBB" ] || die "Cannot find $TestBB"
+[ -f "$TestBB" ] || die "Cannot execute $TestBB (Wrong file type)"
 [ -x "$TestBB" ] || die "Cannot execute $TestBB (Permission denied)"
 
 echo "Testing $TestBB"
